### ISSUE TITLE
Version in OpenBSD ports is out of date

### ISSUE THREAD

**Issue by paulsuh** [yellowman/nsh#14]
Output from ports system search (make search name=nsh): 
```
Port:   nsh-1.0.20140503p1
Path:   shells/nsh
Info:   network switch style shell
Maint:  The OpenBSD ports mailing-list <ports@openbsd.org>
Index:  shells net
L-deps: 
B-deps: 
R-deps: 
Archs:  any
```
I'm willing to take over as maintainer for this.

**Comment by yellowman** [comment]
Do you have commit access on cvs.openbsd.org ?

Paul Suh [notifications@github.com] wrote:
> Output from ports system search (make search name=nsh): 
> ```
> Port:   nsh-1.0.20140503p1
> Path:   shells/nsh
> Info:   network switch style shell
> Maint:  The OpenBSD ports mailing-list <ports@openbsd.org>
> Index:  shells net
> L-deps: 
> B-deps: 
> R-deps: 
> Archs:  any
> ```
> I'm willing to take over as maintainer for this. 
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/yellowman/nsh/issues/14

-- 
The bums will always lose

**Comment by paulsuh** [comment]
No, is it a necessity?

**Comment by yellowman** [comment]
Not entirely. You can submit patches to the ports mailing list to bring it up to the current github version, and other people will commit them. You can also send them to me and I'll attempt to get them committed.
