### ISSUE TITLE
Small porting to NetBSD

### ISSUE THREAD

**Issue by muhammadn** [yellowman/nsh#141]
I started work on porting NSH to NetBSD just to see how it goes. Removed OpenBSD specific guts out to build the base code to build upon.

The final target would be to port it to FreeBSD and hopefully it will make it's way to OPNSense (hopefully).

Thanks for maintaining NSH!

<img width="872" alt="Screenshot 2023-07-17 at 9 35 36 PM" src="https://github.com/yellowman/nsh/assets/3349747/3436aa29-f570-4096-9aa7-12dc9ec21e03">

**Comment by yellowman** [comment]
Please submit patches to the mailing list and we can look at incorporating it into the base tree

**Comment by muhammadn** [comment]
I think it's going to be a challenge to support different BSDs from current codebase. Do I need to maintain a separate fork for other BSD or should i start adding support for other BSD (like Net/FreeBSD) on this repo codebase?

Maybe i'll discuss more at the mailing list. There is much to be done for my port because i removed *all* of OpenBSD platform specific code including the functionality to keep it as basic as possible and start to add FreeBSD's platform specific features there.

<img width="782" alt="Screenshot 2023-07-18 at 2 26 04 PM" src="https://github.com/yellowman/nsh/assets/3349747/4515eb1a-0032-4342-b982-e8c03cf68570">
