### ISSUE TITLE
nsh assumes it is alwasys invoked from rdomain 0  (this is not necessarily true 

### ISSUE THREAD

**Issue by smytht** [yellowman/nsh#162]
nshdoas root@fw2001.wirelessconnect.eu password:
fw2001.wirelessconnect.eu(p)/show bgp summary
bgpctl: connect: /var/run/bgpd.sock.240: No such file or directory
fw2001.wirelessconnect.eu(p)/rtable 0
fw2001.wirelessconnect.eu(p)/show bgp summary
bgpctl: connect: /var/run/bgpd.sock.240: No such file or directory
fw2001.wirelessconnect.eu(p)/rtable 240
fw2001.wirelessconnect.eu(p-rtable 240)/rtable 0
fw2001.wirelessconnect.eu(p)/show bgp summary
bgpctl: connect: /var/run/bgpd.sock.240: No such file or directory
fw2001.wirelessconnect.eu(p)/

when running sshd in a different rdomain (i.e.) a management network ... 
and when a client logs into the firewall via the managment network / rdomain (using sshd) which is running in that rdomain
nsh correctly knows that it is in rdomain240, but it cant get back to rdomain0.
nsh needs to be able to  be able to execute into the default rdomain,  rdomain 0  and then the user can correctly switch between various rdomains on the box ... 

Or  
nsh must be aware what rdomain it is running in and jump to that rdomain config mode and allow the user to switch back to the default rdomain by typing rtable 0 at the prompt ...

----------------
steps to replicate 

1) create a new rdomain 
rtable 240

1a) in the rtable 240 enable configuration mode 
config

2) configure an interface with rdomain 240
interface em3
rdomain 240
inet 10.10.10.10/24
!

3) edit sshd config and copy in the default sshd config 
 sshd edit 

4) enable sshd 

5) write config

reboot 
ssh into the management interface

**Comment by stspdotname** [comment]
Sent a patch to the list for, and also here: git clone --branch rtable anonymous@git.chirpysoft.be:nsh.git

**Comment by smytht** [comment]
OK tom Tested  on thee system, and it worked relally nice 
please push in 
git clone --branch rtable anonymous@git.chirpysoft.be:nsh.git

OpenBSD 7.6-beta (GENERIC.MP) #316: Sun Sep 15 20:13:29 MDT 2024
% Functionality is limited without root privileges.
% The 'enable' command will switch to the root user.
% NSH v1.2.2-current; Compiled by root@fw2001.wirelessconnect.eu on 17-Sep-24 11:29
fw2001.wirelessconnect.eu(rtable 240)/su
doas is not enabled, /etc/doas.conf: No such file or directory
% No rule for fireman found in /etc/doas.conf; root password required
nshdoas root@fw2001.wirelessconnect.eu password:
nshdoas: Authentication failed
nshdoas root@fw2001.wirelessconnect.eu password:
fw2001.wirelessconnect.eu(p-rtable 240)/rtable 0
fw2001.wirelessconnect.eu(p)/show bgp summary
Neighbor                   AS    MsgRcvd    MsgSent  OutQ Up/Down  State/PrfRcvd
OC-AS62129-RR-1         62129     412027       2064     0 17:10:49 971167/1300000
OC-AS62129-RR-2         62129     384276       2064     0 17:10:49 971166/1500000
fw2001.wirelessconnect.eu(p)/rtable 240
fw2001.wirelessconnect.eu(p-rtable 240)/ping 10.64.24.1
PING 10.64.24.1 (10.64.24.1): 56 data bytes
64 bytes from 10.64.24.1: icmp_seq=0 ttl=64 time=0.253 ms
64 bytes from 10.64.24.1: icmp_seq=1 ttl=64 time=0.288 ms
q64 bytes from 10.64.24.1: icmp_seq=2 ttl=64 time=0.295 ms
uit
64 bytes from 10.64.24.1: icmp_seq=3 ttl=64 time=0.294 ms
64 bytes from 10.64.24.1: icmp_seq=4 ttl=64 time=0.279 ms
ext64 bytes from 10.64.24.1: icmp_seq=5 ttl=64 time=0.274 ms
it
64 bytes from 10.64.24.1: icmp_seq=6 ttl=64 time=0.289 ms
64 bytes from 10.64.24.1: icmp_seq=7 ttl=64 time=0.305 ms
^C
--- 10.64.24.1 ping statistics ---
8 packets transmitted, 8 packets received, 0.0% packet loss
round-trip min/avg/max/std-dev = 0.253/0.285/0.305/0.015 ms
fw2001.wirelessconnect.eu(p-rtable 240)/show bgp summary
bgpctl: connect: /var/run/bgpd.sock.240: No such file or directory
fw2001.wirelessconnect.eu(p-rtable 240)/rtable 0
fw2001.wirelessconnect.eu(p)/show bgp summary
Neighbor                   AS    MsgRcvd    MsgSent  OutQ Up/Down  State/PrfRcvd
OC-AS62129-RR-1         62129     416124       2100     0 17:28:41 971204/1300000
OC-AS62129-RR-2         62129     387868       2100     0 17:28:41 971203/1500000
fw2001.wirelessconnect.eu(p)/show ospf
ospf    ospf6
fw2001.wirelessconnect.eu(p)/show ospf summary
Router ID: 5.134.88.126
Uptime: 17:31:02
RFC1583 compatibility flag is disabled
SPF delay is 1000 msec(s), hold time between two SPFs is 5000 msec(s)
Number of external LSA(s) 178 (Checksum sum 0x565feb)
Number of areas attached to this router: 1

Area ID: 0.0.0.0
  Number of interfaces in this area: 5
  Number of fully adjacent neighbors in this area: 4
  SPF algorithm executed 3 time(s)
  Number LSA(s) 12 (Checksum sum 0x638a4)
fw2001.wirelessconnect.eu(p)/
