### ISSUE TITLE
ike editor lack of info in ike parser  in nsh in openbsd6.0 amd64 ports 

### ISSUE THREAD

**Issue by smytht** [yellowman/nsh#25]
if you use the iked editor 
if you have one or 2 spaces after the trailing \  the policy is not loaded properly and there is no indication from the interpreter of where the issue is,

**Comment by yellowman** [comment]
can you test and see if this happens using iked by itself? create iked.conf with spaces after \
and see if the same thing happens. nsh dumps the contents of nshrc into /var/run/iked.conf.x where x is the rtable/rdomain

**Comment by ogmaconnect** [comment]
This issue has been dealt with years ago and can bel closed.
