### ISSUE TITLE
iked rdomain support 

### ISSUE THREAD

**Issue by smytht** [yellowman/nsh#26]
it would be nice if  you could  specify an iked policy inside an rdomain, 
this is achived in openbsd by running adding the following line in a hostname.if config file 

up 
media auto
!/sbin/route -T 2 exec /sbin/iked -f /etc/iked2.conf
other tunnel setup commands here after iked in rdomain 2 is setup 

Eof hostname.if

not forgetting to create an enc2 interface inside rdomain 2 also ... (this part  is covered fine in nsh config)

**Comment by yellowman** [comment]
This support already exists

see the table in ctl.c:
{ "ike",        "IPsec IKEv2",ctl_ike,  IKECONF_TEMP,   0600, 0, RT_TABLEID_MAX },

ike commands can be specified under any rtable from 1 to RT_TABLEID_MAX

each iked instance is a separate config/daemon according to typical rtable support
