### ISSUE TITLE
nsh causes a panic when reboot is executed from inside nsh Openbsd 6.0 amd64 standard package

### ISSUE THREAD

**Issue by smytht** [yellowman/nsh#27]
in OpenBSD 6.0 amd64  on the PC engines APU C2 Board  
I have seen an issue  
when reboot command is issued in nsh privileged mode on a PC engines APUC2 board,
if you run !ksh and then reboot there is no panic ... 

im not sure what the difference between NSH calling reboot and ksh calling reboot is 

I was running nsh /ksh  as root

**Comment by yellowman** [comment]
Yeah the minimal 'reboot' implementation was not such a good idea. I replaced it with an external call to /sbin/reboot so it is already fixed in the latest tree.

**Comment by smytht** [comment]
Thanks for that cheers,
