### ISSUE TITLE
IPv6 autoconf addresses are saved

### ISSUE THREAD

**Issue by sthen** [yellowman/nsh#3]
If saving current config with write-config, all configured IPv6 addresses including autoconf and autoconfprivacy addresses are saved, these should probably be skipped. Looks to be necessary to use SIOCGIFAFLAG_IN6 to fetch the flags needed to determine this.

**Comment by yellowman** [comment]
It appears this was fixed on day after your bug report :)

https://github.com/yellowman/nsh/commit/c96bb949e4cd62bdc592930b64ad2f74a9ba117d#diff-eba6dbf5f09d47edb7cd3b629e2fe87a
