### ISSUE TITLE
Bogus arp 224.0.0.0 line if multicast enabled

### ISSUE THREAD

**Issue by sthen** [yellowman/nsh#4]
On a system with 'multicast_host=YES' in rc.conf.local a route to 224/4 is installed pointing out the default interface; write-config translates this to a bogus line "arp 224.0.0.0 " (with the space at the end).

**Comment by yellowman** [comment]
fixed https://github.com/yellowman/nsh/commit/95556998efd73f383f6203449f0cb625d49704f3
