### ISSUE TITLE
various flags/options for pppoe not saved

### ISSUE THREAD

**Issue by sthen** [yellowman/nsh#5]
authname/authkey/authproto and pppoedev are essential, some other flags may also be useful.

(also related, various flags for 802.11 interfaces could be useful; wpa, wpakey).

**Comment by sthen** [comment]
Ugh: seems that authkey can't be fetched from the kernel. I'm hacking around this for now by configuring pppoe separately using netstart, and stripping out interface pppoe0 in save.sh...

**Comment by yellowman** [comment]
Stuart Henderson [notifications@github.com] wrote:
> Ugh: seems that authkey can't be fetched from the kernel. I'm hacking around this for now by configuring pppoe separately using netstart, and stripping out interface pppoe0 in save.sh...
> 

This isn't necessary. There is a mechanism to save this using sqlite. I'll provide a patch.

**Comment by yellowman** [comment]
i suspect peerkey needs to be saved too

**Comment by yellowman** [comment]
https://github.com/yellowman/nsh/commit/1487471bf46ac8dee4b2e7e67af1770ee37dd0af
